services:
  astro:
    image: ghcr.io/florivdg/toolio/toolio:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_FILE_NAME=/data/sqlite.db
    networks:
      - traefik_system_traefik
    volumes:
      - ./data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.${TRAEFIK_DNS}.rule=(Host(`${TRAEFIK_DNS}.flori.cloud`))
      - traefik.http.routers.${TRAEFIK_DNS}.entrypoints=websecure
      - traefik.http.routers.${TRAEFIK_DNS}.tls=true
      - traefik.http.routers.${TRAEFIK_DNS}.tls.certresolver=le
      - traefik.http.services.${TRAEFIK_DNS}.loadbalancer.server.port=4321
      - traefik.docker.network=traefik_system_traefik

networks:
  traefik_system_traefik:
    external: true
